framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%lexaura.mailsender%'
#            recipients: ['foo@example.com', 'bar@example.com']
        headers:
            From: 'No-reply - Fransylva <%lexaura.mailsender%>'
#            Bcc: 'baz@example.com'
#            X-Custom-Header: 'foobar'
